site_name: My Docs
site_url: https://example.com/
site_name: 好望云服务POC生态地图
repo_name: 'holo-sens/ecosystem'

theme:
  name: 'material'
  language: 'zh'
  palette:
    primary: 'Indigo'
    accent: 'Indigo'
  feature:
    tabs: false

nav:
- 智能应用场景:
  - 智慧养殖:
    - 方案架构: Intelligence_Application/cultivation/Framework.md
    - '5.1 <--> 8.0': Business_Intelligence/FineBI_5.1.md
  - 智慧门店:
    - 官网链接  
  - 智慧4S店:
    - 官网链接    
- POC项目简介:
  - 智慧养殖:
    - 牧原项目  
    - 双胞胎项目  
  - 智慧门店:
    - RY
  - 智慧4S店:  
    - BYD

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: false
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg
      #emoji_generator: !!python/name:pymdownx.emoji.to_png_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_svg_sprite
      #emoji_generator: !!python/name:pymdownx.emoji.to_awesome
      #emoji_generator: !!python/name:pymdownx.emoji.to_alt
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde
  
extra_javascript:
  - 'js/jq.js'
  - 'js/extra.js'
  - 'js/baidu-tongji.js'